$wallpaper = ~/.config/quickshell/themes/lotus/wallpapers/lotus.jpg

general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  path = $wallpaper
  blur_passes = 2
  brightness = 0.55
}

input-field {
  monitor =
  size = 420, 64
  position = 0, -40
  halign = center
  valign = center
  inner_color = rgba(26, 27, 38, 0.85)
  outer_color = rgba(122, 162, 247, 1.0)
  font_color = rgb(192, 202, 245)
  placeholder_text = Password
  outline_thickness = 2
  rounding = 10
  fade_on_empty = false
}
