general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(61afefcc)
  col.inactive_border = rgba(3b414dcc)
  layout = dwindle
}

decoration {
  rounding = 4
  shadow {
    enabled = false
  }
  blur {
    enabled = true
    size = 5
    passes = 2
  }
}

animations {
  enabled = true
}
