$mod = SUPER
$terminal = ghostty
$browser = firefox
$fileManager = nautilus --new-window

source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/live.conf

monitor = ,preferred,auto,1

exec-once = quickshell --no-duplicate
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

input {
  kb_layout = us
  kb_options = ctrl:nocaps,altwin:swap_alt_win
  follow_mouse = 1

  touchpad {
    natural_scroll = false
  }
}

dwindle {
  pseudotile = true
  preserve_split = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
