windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = float-settings-windows
  match:class = ^(org.pulseaudio.pavucontrol|blueman-manager)$
  float = yes
}

windowrule {
  name = ghostty-popup
  match:class = ^ghostty-popup$
  float = yes
  center = yes
  size = 80% 80%
  workspace = special:terminal silent
}
